import numpy as np
from numpy .linalg import inv, det

In [3]:
a = [1,3,5,7,9]
print(a)
b = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
print(b[0][2:4])

[1, 3, 5, 7, 9]
[5, 7]


In [24]:
# convert array to nparray
np.asarray(a)

array([1, 3, 5, 7, 9])

In [23]:
# Convert list to nparray
d = np.array(a)
print(d)

[1 3 5 7 9]


In [4]:
# joining two list
c = a + b
print(c)

[1, 3, 5, 7, 9, [1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]


In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [8]:
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
# Ndarray attributes
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.itemsize)
print(arr2.data)

2
(2, 4)
8
int32
4


In [10]:
# Create array
#range function to create arrays
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Functions to create arrays of certain default values
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.ones_like((2,2))

array([1, 1])

In [14]:
np.empty((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.full((2,3),2)

array([[2, 2, 2],
       [2, 2, 2]])

In [29]:
# Create identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.identity(2, dtype = None)

array([[1., 0.],
       [0., 1.]])

In [34]:
#Array arithmetic
arr=np.array([[1,2,3],[4,5,6]])
#■ Multiplication
arr*arr
arr*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [35]:
#■ Addition/Deduction
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [36]:
#■ Division
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [37]:
#■ Comparison
arr2=np.array([[0,4,7],[7,2,10]])
arr2>arr

array([[False,  True,  True],
       [ True, False,  True]])

In [38]:
### another way to create a multi-dimensional array
np.arange(10, 20) . reshape((2,5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
a = np.arange(1,10). reshape((3,3))
print('a',a)
#Slicing nparray
#Select after second row
print("\n a[1::] \n",a[2::])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[1::] 
 [[7 8 9]]


In [63]:
print('a',a)
#Select before second row
print("\n a[::2] \n",a[::2])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[::3] 
 [[1 2 3]
 [7 8 9]]


In [70]:
print('a',a)
#Select second row
print("\n a[2] \n",a[2])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[2] 
 [7 8 9]


In [73]:
print('a',a)
#Select all rows second column
print("\n a[:,2] \n",a[:,2])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[:,2] 
 [3 6 9]


In [75]:
print('a',a)
#Select before second row
print("\n a[:2] \n",a[:2])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[:2] 
 [[1 2 3]
 [4 5 6]]


In [79]:
print('a',a)
#Select before second row after first column
print("\n a[:2,1:] \n",a[:2,1:])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[:2,1:] 
 [[2 3]
 [5 6]]


In [80]:
print('a',a)
#Select after first column
print("\n a[:2] \n",a[:,1:])

a [[1 2 3]
 [4 5 6]
 [7 8 9]]

 a[:2] 
 [[2 3]
 [5 6]
 [8 9]]


In [84]:
#set seed
np.random.seed(123)

In [104]:
#Random number
#Random number from standard normal distribution
np.random.normal(size=(4,4))

array([[-0.38753876, -0.80352208,  0.93898923,  0.43781947],
       [ 1.14109158,  0.17145177, -1.54957884, -0.97402348],
       [-1.0491106 , -0.46483438, -0.49055989,  1.0007457 ],
       [ 2.14851419,  1.43240926, -0.13335333,  0.00577405]])

In [105]:
#Random integers from a range
np.random.randint(1,10,size=(3,3))

array([[3, 3, 4],
       [3, 7, 8],
       [2, 4, 9]])

In [110]:
##numpy array with random numbers following the standard normal distribution 
#The size of the array is 3 rows and 4 columns
a = np.random.normal(size=(3,4))
print("standard normal array \n",a)

standard normal array 
 [[-1.25965858 -0.38548797  0.75838308 -3.78464183]
 [-1.21926273 -0.36950196  0.12348275 -0.53309587]
 [ 0.56791429 -0.34861261 -0.68503137  2.55436834]]


In [111]:
#Slice the array, we only want the 2nd and 3rd rows
a = a[1:]
print("Display only second and third row \n",a)

Display only second and third row 
 [[-1.21926273 -0.36950196  0.12348275 -0.53309587]
 [ 0.56791429 -0.34861261 -0.68503137  2.55436834]]


In [112]:
# Check the shape of the array now
print("Shape of array",a.shape)

Shape of array (2, 4)


In [113]:
#Multiply the elements in the array by 2 
a = a*2
print("Multiply the elements in the array by 2 \n", a)

Multiply the elements in the array by 2 
 [[-2.43852545 -0.73900392  0.2469655  -1.06619174]
 [ 1.13582858 -0.69722521 -1.37006275  5.10873668]]


In [114]:
#Change the data type to integer
a = a.astype(np.int32)
print("Change the data type to integer \n", a)

Change the data type to integer 
 [[-2  0  0 -1]
 [ 1  0 -1  5]]


In [115]:
#Change the value for the 4th element in the 2nd row to 10
a[1,3] = 10
a

array([[-2,  0,  0, -1],
       [ 1,  0, -1, 10]])

In [118]:
#Matrix operaions
x=np.random.randn(5,5)
## computes the dot product of x and its transpose
mat=x.T.dot(x)
mat

array([[ 8.38314655,  2.97169249, -0.69954805, -0.42149052, -2.62148499],
       [ 2.97169249,  4.18197921,  0.58441559,  1.23137837, -3.01702578],
       [-0.69954805,  0.58441559,  7.30502761, -0.7262227 ,  3.17121887],
       [-0.42149052,  1.23137837, -0.7262227 ,  1.36412311, -1.38477623],
       [-2.62148499, -3.01702578,  3.17121887, -1.38477623,  7.92224205]])

In [121]:
# Inverse of matrix
inv(mat)

array([[ 2.64216092e-01, -3.26169246e-01,  9.36710281e-02,
         4.26145951e-01,  2.07383729e-04],
       [-3.26169246e-01,  9.05017365e-01, -2.74470068e-01,
        -8.65600823e-01,  1.95292462e-01],
       [ 9.36710281e-02, -2.74470068e-01,  2.49837458e-01,
         2.83924740e-01, -1.23909760e-01],
       [ 4.26145951e-01, -8.65600823e-01,  2.83924740e-01,
         1.81191148e+00,  1.44276926e-02],
       [ 2.07383729e-04,  1.95292462e-01, -1.23909760e-01,
         1.44276926e-02,  2.52790830e-01]])

In [122]:
#determinant of matrix
det(mat)

402.446828498397

In [132]:
#NumPy functions
arr=np.arange(4)
print('arr \n',arr)
print('square root of each element of arr \n',np.sqrt(arr))
print('expose of each element of arr \n',np.exp(arr))
arr2 = np.array([4,3,9,1])
print('arr2 \n',arr2)
print('Maximum of arr and arr2 \n',np.maximum(arr,arr2))

arr 
 [0 1 2 3]
square root of each element of arr 
 [0.         1.         1.41421356 1.73205081]
expose of each element of arr 
 [ 1.          2.71828183  7.3890561  20.08553692]
arr2 
 [4 3 9 1]
Maximum of arr and arr2 
 [4 3 9 3]


In [147]:
#Statistical methods
arr=np.array([4,5,2,9])
print('arr \n',arr)
print('arr mean:\t',arr.mean())
print('arr mean:\t',np.mean(arr))
print('arr sum:\t',arr.sum())
print('arr Standard deviation:\t',arr.std())
print('arr #Variance:\t',arr.var())
print('arr Min element:\t',arr.min())
print('arr Max element:\t',arr.max())
print('arr Indices of Min element:\t',arr.argmin())
print('arr Indices of Max element:\t',arr.argmax())

arr 
 [4 5 2 9]
arr mean:	 5.0
arr mean:	 5.0
arr sum:	 20
arr Standard deviation:	 2.5495097567963922
arr #Variance:	 6.5
arr Min element:	 2
arr Max element:	 9
arr Indices of Min element:	 2
arr Indices of Max element:	 3


In [148]:
# Broadcasting
#Sometimes even when two arrays are of different shapes, arithmetic still can work between them.
arr1=np.arange(5)
arr2=np.random.normal(size=(4,5))
arr1-arr2

array([[ 2.01538001,  0.78511579,  3.05082586,  1.10532412,  2.89489852],
       [-1.48206762,  1.59970757,  0.58710475,  3.52590215,  1.36431463],
       [ 1.36820102,  2.76212724,  2.5538826 ,  1.88099565,  4.35229011],
       [-0.39713688,  0.86732042,  0.95214062,  3.06360765,  4.67240881]])

In [157]:
#Create a 3*3 array of random integers between 10 and 50, name it arr1 and sort it.
arr1 = np.random.randint(10,50, size=(3,3))
print("arr1 \n",arr1)
arr1.sort()
print("arr1 after sorting \n",arr1)

arr1 
 [[49 10 23]
 [17 16 39]
 [34 48 25]]
arr1 after sorting 
 [[10 23 49]
 [16 17 39]
 [25 34 48]]


In [158]:
#Input data [2.3, 7, 9, 0.5, 21, 1, 6, 4.1, 0.3, 90] as a 1*10 array, name it arr2
arr2 = [2.3, 7, 9, 0.5, 21, 1, 6, 4.1, 0.3, 90]
print("arr2 \n",arr2)

arr2 
 [2.3, 7, 9, 0.5, 21, 1, 6, 4.1, 0.3, 90]


In [163]:
#Then take the first 9 values from arr2 to create a 3*3 array of which the name is arr3.
arr3 = np.array(arr2[:9]).reshape(3,3)
print("arr3 \n",arr3)

arr3 
 [[ 2.3  7.   9. ]
 [ 0.5 21.   1. ]
 [ 6.   4.1  0.3]]


In [164]:
#Display arr1, arr2, arr3
print("arr1 \n",arr1)


print("arr3 \n",arr3)

arr1 
 [[10 23 49]
 [16 17 39]
 [25 34 48]]
arr2 
 [2.3, 7, 9, 0.5, 21, 1, 6, 4.1, 0.3, 90]
arr3 
 [[ 2.3  7.   9. ]
 [ 0.5 21.   1. ]
 [ 6.   4.1  0.3]]


In [165]:
#Display the shape and the data type of the array arr3.
print("shape of arr3 \t",arr3.shape)
print("shadata typepe of arr3 \t",arr3.dtype)

shape of arr3 	 (3, 3)
shadata typepe of arr3 	 float64


In [166]:
#Calculate the product of arr1 and arr3.
print("Product of arr1 and arr3 \n", arr1*arr3)

Product of arr1 and arr3 
 [[ 23.  161.  441. ]
 [  8.  357.   39. ]
 [150.  139.4  14.4]]


In [167]:
#Check if each value in arr1 is greater than the corresponding value in arr3.
print("Check if each value in arr1 is greater than the corresponding value in arr3 \n", arr1 > arr3)

Check if each value in arr1 is greater than the corresponding value in arr3 
 [[ True  True  True]
 [ True False  True]
 [ True  True  True]]


In [168]:
#Calculate the mean of all values in arr1.
print("Mean of arr1", arr1.mean())

Mean of arr1 29.0


In [169]:
#Find in arr2 the value that is closest to 5.
print("arr2 \n",arr2)
print("arr2 the value that is closest to 5",np.abs(np.array(arr2)-5).argmin())

arr2 
 [2.3, 7, 9, 0.5, 21, 1, 6, 4.1, 0.3, 90]
arr2 the value that is closest to 5 7


In [172]:
#Complete these matrix calculations: multiplication between arr1 and
#arr3, inverse of arr1, determinant of arr3, and the transpose of the product
#of arr1 and its inverse.
print("multiplication between arr1 and arr3 \n", np.dot(arr1,arr3))

multiplication between arr1 and arr3 
 [[ 328.5  753.9  127.7]
 [ 279.3  628.9  172.7]
 [ 362.5 1085.8  273.4]]


In [179]:
print("Inverse of arr1 \n", inv(arr1))

Inverse of arr1 
 [[-0.09286235  0.10233066  0.01165331]
 [ 0.03769119 -0.13565186  0.07174071]
 [ 0.02166788  0.04278951 -0.03605244]]


In [175]:
print("determinant of arr3 \n", det(arr3))

determinant of arr3 
 -1069.5400000000006


In [181]:
print("transpose of the product of arr1 and its inverse \n", arr1.dot(inv(arr1)).T)

transpose of the product of arr1 and its inverse 
 [[ 1.00000000e+00 -1.11022302e-16 -2.22044605e-16]
 [-4.16333634e-16  1.00000000e+00 -4.44089210e-16]
 [-1.59594560e-16 -1.17961196e-16  1.00000000e+00]]


In [184]:
import csv

In [203]:
#Import the csv. file “Athlete.csv”. The data show several Olympic athletes’
#information including age, height, weight, and year of participating in Olympic games
with open('Athlete.csv', 'r') as f:
    athlete = list(csv.reader(f,delimiter=","))

In [204]:
# a) Display the first 5 rows (including headers) of the data.
athlete[:5]

[['ID', 'Age', 'Height', 'Weight', 'Year'],
 ['1', '24', '180', '80', '1992'],
 ['2', '23', '170', '60', '2012'],
 ['5', '21', '185', '82', '1988'],
 ['5', '21', '185', '82', '1988']]

In [205]:
#Create a NumPy array for the data. Show how many rows and columns are there in the data.
ath = np.array(athlete)
print("rows and columns are there in the data",ath.shape)

rows and columns are there in the data (28, 5)


In [206]:
#c) Overwrite the Year value of the 2nd row (that is, the athlete whose ID is 1) with 1993
# Display only the Year column to check if the value has been successfully changed. 
ath[1,4] = 1993
print('Year column',ath[:,4])

Year column ['Year' '1993' '2012' '1988' '1988' '1992' '1992' '1994' '1994' '1992'
 '1992' '1992' '1992' '1994' '1994' '1994' '1994' '1992' '1992' '1992'
 '1992' '1994' '1994' '1994' '1994' '2002' '1980' '2000']


In [207]:
#d) Deduct 10 from all athletes’ weights and show results.
ath=np.array(athlete[1:],dtype=np.float16)
print('Weight column \n',ath[:,3])
ath[:,3] = ath[:,3]-10
print("Weight after deduction \n",ath[:,3])

Weight column 
 [80.  60.  82.  82.  82.  82.  82.  82.  75.  75.  75.  75.  75.  75.
 75.  75.  72.  72.  72.  72.  72.  72.  72.  72.  96.  76.5 70. ]
Weight after deduction 
 [70.  50.  72.  72.  72.  72.  72.  72.  65.  65.  65.  65.  65.  65.
 65.  65.  62.  62.  62.  62.  62.  62.  62.  62.  86.  66.5 60. ]


In [208]:
#Add a new column to the array to show the ratio of weight to height of each athlete
print("ath shape",ath.shape)
whr = np.reshape(ath[:,3]/ath[:,2], (27,1))
whr
ath=np.append(ath, whr, axis=1)
print(ath)

[[1.000e+00 2.400e+01 1.800e+02 7.000e+01 1.992e+03 3.889e-01]
 [2.000e+00 2.300e+01 1.700e+02 5.000e+01 2.012e+03 2.942e-01]
 [5.000e+00 2.100e+01 1.850e+02 7.200e+01 1.988e+03 3.892e-01]
 [5.000e+00 2.100e+01 1.850e+02 7.200e+01 1.988e+03 3.892e-01]
 [5.000e+00 2.500e+01 1.850e+02 7.200e+01 1.992e+03 3.892e-01]
 [5.000e+00 2.500e+01 1.850e+02 7.200e+01 1.992e+03 3.892e-01]
 [5.000e+00 2.700e+01 1.850e+02 7.200e+01 1.994e+03 3.892e-01]
 [5.000e+00 2.700e+01 1.850e+02 7.200e+01 1.994e+03 3.892e-01]
 [6.000e+00 3.100e+01 1.880e+02 6.500e+01 1.992e+03 3.457e-01]
 [6.000e+00 3.100e+01 1.880e+02 6.500e+01 1.992e+03 3.457e-01]
 [6.000e+00 3.100e+01 1.880e+02 6.500e+01 1.992e+03 3.457e-01]
 [6.000e+00 3.100e+01 1.880e+02 6.500e+01 1.992e+03 3.457e-01]
 [6.000e+00 3.300e+01 1.880e+02 6.500e+01 1.994e+03 3.457e-01]
 [6.000e+00 3.300e+01 1.880e+02 6.500e+01 1.994e+03 3.457e-01]
 [6.000e+00 3.300e+01 1.880e+02 6.500e+01 1.994e+03 3.457e-01]
 [6.000e+00 3.300e+01 1.880e+02 6.500e+01 1.994e+03 3.4

In [209]:
#f) Create a 1*6 random array following standard normal distribution. 
#Add this new array to the athlete array and see what happens.
nrm = np.random.normal(size = (1,6))
print("standard normal distribution array",nrm)
print("add standard normal distribution to ath array",nrm+ath)

standard normal distribution array [[ 0.8373722  -1.73322164 -1.26620989  0.23590947  0.54790236  0.21719083]]
add standard normal distribution to ath array [[1.83737220e+00 2.22667784e+01 1.78733790e+02 7.02359095e+01
  1.99254790e+03 6.06106845e-01]
 [2.83737220e+00 2.12667784e+01 1.68733790e+02 5.02359095e+01
  2.01254790e+03 5.11380282e-01]
 [5.83737220e+00 1.92667784e+01 1.83733790e+02 7.22359095e+01
  1.98854790e+03 6.06350985e-01]
 [5.83737220e+00 1.92667784e+01 1.83733790e+02 7.22359095e+01
  1.98854790e+03 6.06350985e-01]
 [5.83737220e+00 2.32667784e+01 1.83733790e+02 7.22359095e+01
  1.99254790e+03 6.06350985e-01]
 [5.83737220e+00 2.32667784e+01 1.83733790e+02 7.22359095e+01
  1.99254790e+03 6.06350985e-01]
 [5.83737220e+00 2.52667784e+01 1.83733790e+02 7.22359095e+01
  1.99454790e+03 6.06350985e-01]
 [5.83737220e+00 2.52667784e+01 1.83733790e+02 7.22359095e+01
  1.99454790e+03 6.06350985e-01]
 [6.83737220e+00 2.92667784e+01 1.86733790e+02 6.52359095e+01
  1.99254790e+03 5.62

In [210]:
#Create a vectorize function that adds 1 to the original value if the original value is less than 0.
def vec(a):
    if a < 0:
        return a+1
    else:
        return a

In [211]:
 # Run the function on the normal distribution array created in f).
vfunc=np.vectorize(vec)
vfunc(nrm)

array([[ 0.8373722 , -0.73322164, -0.26620989,  0.23590947,  0.54790236,
         0.21719083]])

In [212]:
# Create a 4*3 NumPy array of random integers between 10 and 100, name it arr1 and sort it
arr1 = np.random.randint(1,100,size=(4,3))
print("arr1\n",arr1)
arr1.sort()
print("arr1 after sorting\n",arr1)

arr1
 [[ 1 98 31]
 [21 24 19]
 [61 60 85]
 [25 20 26]]
arr1 after sorting
 [[ 1 31 98]
 [19 21 24]
 [60 61 85]
 [20 25 26]]


In [213]:
#Display the shape and the data type of arr1. 
print("Shape of array",arr1.shape)
print("Datatype of array",arr1.dtype)


Shape of array (4, 3)
Datatype of array int32


In [214]:
#Create a new 4*3 array arr2 in which each element is 1.5 times the element at the corresponding location in arr1. 
arr2 = np.array(arr1*1.5).reshape(4,3)
print("arr2 \n",arr2)

arr2 
 [[  1.5  46.5 147. ]
 [ 28.5  31.5  36. ]
 [ 90.   91.5 127.5]
 [ 30.   37.5  39. ]]


In [217]:
#Slice arr2 to drop the first row. 
arr2 = arr2[1:]
print("arr2 after dropping first row \n",arr2)

arr2 after dropping first row 
 [[ 28.5  31.5  36. ]
 [ 90.   91.5 127.5]
 [ 30.   37.5  39. ]]


In [218]:
#Calculate the mean of all values in arr1. 
print("Mean of arr1", arr1.mean())

Mean of arr1 39.25


In [219]:
#View arr1 and arr2 as matrices
print("arr1 \n",arr1)
print("arr2 \n",arr2)

arr1 
 [[ 1 31 98]
 [19 21 24]
 [60 61 85]
 [20 25 26]]
arr2 
 [[ 28.5  31.5  36. ]
 [ 90.   91.5 127.5]
 [ 30.   37.5  39. ]]


In [220]:
#create a new matrix arr3 which is the dot product of arr1 and arr2
arr3 = arr1.dot(arr2)
print("arr3 \n",arr3)

arr3 
 [[ 5758.5  6543.   7810.5]
 [ 3151.5  3420.   4297.5]
 [ 9750.  10659.  13252.5]
 [ 3600.   3892.5  4921.5]]


In [221]:
#what is the shape of arr3
print("Shape of arr3 ",arr3.shape)

Shape of arr3  (4, 3)
